### ISSUE TITLE
How is this any different from kitchen-nodes?

### ISSUE THREAD

**Issue by rneu31** [scopenco/kitchen-chefzero-nodes#1]
I tried to use this as well. I am converging one linux box, followed by a windows machine. I need the IP address of the linux machine in a recipe running on the Windows machine. On the windows machine, there are .json files created for the linux and windows nodes in %temp%\kitchen\nodes. 

When doing the search it looks like it's only searching the nodes/windows.json file. Is this true? How do I access the linux.json file to get the IP address?

**Comment by scopenco** [comment]
@rneu31 you have to search linux node and ip address will be accessible in chef attribute node['ipaddress']. Something like this in recipe
```
linux_node = search(:node, "recipes::myrecipe")
pp linux_node['ipaddress']
```
